version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "[%(levelname)-7s] %(name)-20s %(message)s"
  full:
    format: "%(asctime)s - [%(levelname)-7s] %(name)-20s %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO 
    formatter: simple
    stream: ext://sys.stdout
  watched_file_handler:
    class: logging.handlers.WatchedFileHandler
    level: INFO
    formatter: full
    filename: enocean.log
    encoding: utf8
root:
  level: INFO
  handlers:
  - console
  - watched_file_handler
